# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('loc', models.CharField(default='0,0', max_length=20)),
                ('desc', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=15)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(default='0,0', max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('tries', models.IntegerField(default=0)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('acceptee', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='accepts', to='coords.hospital')),
                ('intent', models.ManyToManyField(related_name='requests', to='coords.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('car', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('address', models.TextField(default='')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='coords.user'),
        ),
    ]
