# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='password',
            field=models.CharField(default='bla', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='username',
            field=models.CharField(default='santiago', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='acceptee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accepts', to='coords.hospital'),
        ),
    ]
