# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coords', '0002_auto_20160915_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='username',
            field=models.CharField(default='hospital', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
