# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coords', '0003_auto_20160916_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
