# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='anonymous@gmail.com', max_length=30)),
                ('name', models.CharField(default='anonymous@gmail.com', max_length=30)),
                ('query', models.TextField(default='No Content')),
            ],
        ),
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='anonymous@gmail.com', max_length=30)),
            ],
        ),
    ]
